spring:
  datasource:
    username: eledev
    password: eledevodev
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.7:1521:FREE
  jackson:
    default-property-inclusion: non_null
  mvc:
    log-resolved-exception: on
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: oracle

application:
  security:
    jwt:
      secret-key: B3pSB4hhA4ApRtJQVv/FXoKwsCKZtNQ3CM81G0sPS0tQ+eLsW+6W/EZwE2oEahQK
      expiration: 86400000
      refresh-token:
        expiration: 604800000